name: Chart

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - 'backend/VERSION'
      - 'frontend/VERSION'
  workflow_dispatch:
  workflow_run:
    workflows: ["Images"]
    types: [completed]

permissions:
  contents: write
  packages: write

jobs:
  check-version-changes:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.changes.outputs.version_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for VERSION changes
        id: changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -E "^(backend|frontend)/VERSION$"; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "VERSION files changed, will update chart"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "No VERSION files changed"
          fi

  auto-release:
    needs: check-version-changes
    if: needs.check-version-changes.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update chart with latest image versions
        run: |
          BACKEND_VERSION=$(cat backend/VERSION)
          FRONTEND_VERSION=$(cat frontend/VERSION)
          
          # Update values.yaml with latest versions
          sed -i "/backend:/,/frontend:/ s/tag: \".*\"/tag: \"$BACKEND_VERSION\"/" charts/numberninja/values.yaml
          sed -i "/frontend:/,$ s/tag: \".*\"/tag: \"$FRONTEND_VERSION\"/" charts/numberninja/values.yaml
          
          # Bump chart version
          ./scripts/bump-version.sh chart patch

      - name: Commit and release chart
        run: |
          CHART_VERSION=$(cat charts/numberninja/VERSION)
          BACKEND_VERSION=$(cat backend/VERSION)
          FRONTEND_VERSION=$(cat frontend/VERSION)
          
          git add charts/numberninja/
          git commit -m "🚀 Release chart v$CHART_VERSION

          Updated with:
          - Backend: $BACKEND_VERSION
          - Frontend: $FRONTEND_VERSION
          
          🤖 Auto-released by chart workflow"
          git push

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.1'

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and publish chart
        run: |
          CHART_VERSION=$(cat charts/numberninja/VERSION)
          BACKEND_VERSION=$(cat backend/VERSION)
          FRONTEND_VERSION=$(cat frontend/VERSION)
          
          # Set environment variables for next step
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV
          echo "BACKEND_VERSION=$BACKEND_VERSION" >> $GITHUB_ENV
          echo "FRONTEND_VERSION=$FRONTEND_VERSION" >> $GITHUB_ENV
          
          # Package chart
          helm package charts/numberninja --destination .helm-packages
          
          # Push to OCI registry
          helm push .helm-packages/numberninja-$CHART_VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
          
          echo "✅ Published chart v$CHART_VERSION to oci://ghcr.io/${{ github.repository_owner }}/charts/numberninja:$CHART_VERSION"

      - name: Create Chart Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: helm-chart-numberninja-${{ env.CHART_VERSION }}
          name: Helm Chart v${{ env.CHART_VERSION }}
          body: |
            ## Helm Chart Release v${{ env.CHART_VERSION }}
            
            **OCI Registry**: `oci://ghcr.io/${{ github.repository_owner }}/charts/numberninja:${{ env.CHART_VERSION }}`
            
            ### Image Versions
            - Backend: ${{ env.BACKEND_VERSION }}
            - Frontend: ${{ env.FRONTEND_VERSION }}
            
            ### Installation
            ```bash
            helm install numberninja oci://ghcr.io/${{ github.repository_owner }}/charts/numberninja --version ${{ env.CHART_VERSION }}
            ```
            
            ### Features
            - Complete Kubernetes deployment for NumberNinja
            - Ingress configuration for external access
            - Configurable resource limits and scaling
          draft: false
          prerelease: false

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.1'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list)
        id: list
        run: ct list-changed --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list.outputs.changed == 'true'

      - name: Run chart-testing (install)
        if: steps.list.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

  release:
    needs: lint-test
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release'
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.1'

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Get chart version
        id: version
        run: |
          VERSION=$(cat charts/numberninja/VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Chart version: $VERSION"

      - name: Update chart version in Chart.yaml
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          sed -i "s/version: .*/version: $VERSION/" charts/numberninja/Chart.yaml
          sed -i "s/appVersion: .*/appVersion: \"$VERSION\"/" charts/numberninja/Chart.yaml

      - name: Package Helm chart
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          mkdir -p .helm-packages
          helm package charts/numberninja --destination .helm-packages

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push chart to GHCR OCI registry
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          helm push .helm-packages/numberninja-$VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}/charts