name: Version Bump

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**' 
      - 'charts/**'
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to bump (backend, frontend, chart)'
        required: true
        type: choice
        options:
        - backend
        - frontend
        - chart
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

permissions:
  contents: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      charts: ${{ steps.filter.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - '!backend/VERSION'
            frontend:
              - 'frontend/**'
              - '!frontend/VERSION'
            charts:
              - 'charts/**'
              - '!charts/numberninja/VERSION'

  bump-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.component == 'backend')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump backend version
        run: |
          BUMP_TYPE="${{ github.event.inputs.bump_type || 'patch' }}"
          ./scripts/bump-version.sh backend $BUMP_TYPE

      - name: Commit version bump
        run: |
          NEW_VERSION=$(cat backend/VERSION)
          git add backend/VERSION
          git commit -m "🔖 Bump backend version to $NEW_VERSION

          Automated version bump for backend changes.
          
          🤖 Generated by version-bump workflow"
          git push

  bump-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.component == 'frontend')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump frontend version
        run: |
          BUMP_TYPE="${{ github.event.inputs.bump_type || 'patch' }}"
          ./scripts/bump-version.sh frontend $BUMP_TYPE

      - name: Commit version bump
        run: |
          NEW_VERSION=$(cat frontend/VERSION)
          git add frontend/VERSION frontend/package.json
          git commit -m "🔖 Bump frontend version to $NEW_VERSION

          Automated version bump for frontend changes.
          
          🤖 Generated by version-bump workflow"
          git push

  bump-chart:
    needs: detect-changes
    if: needs.detect-changes.outputs.charts == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.component == 'chart')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get latest image versions for chart
        id: image_versions
        run: |
          # Get latest backend version
          BACKEND_VERSION=$(cat backend/VERSION)
          echo "backend_version=$BACKEND_VERSION" >> $GITHUB_OUTPUT
          
          # Get latest frontend version  
          FRONTEND_VERSION=$(cat frontend/VERSION)
          echo "frontend_version=$FRONTEND_VERSION" >> $GITHUB_OUTPUT
          
          echo "Will reference backend:$BACKEND_VERSION and frontend:$FRONTEND_VERSION"

      - name: Bump chart version
        run: |
          BUMP_TYPE="${{ github.event.inputs.bump_type || 'patch' }}"
          ./scripts/bump-version.sh chart $BUMP_TYPE

      - name: Update chart to reference latest stable images
        run: |
          BACKEND_VERSION="${{ steps.image_versions.outputs.backend_version }}"
          FRONTEND_VERSION="${{ steps.image_versions.outputs.frontend_version }}"
          
          # Update values.yaml to reference the latest stable image versions
          sed -i "s|repository: .*backend.*|repository: ghcr.io/${{ github.repository }}/backend|" charts/numberninja/values.yaml
          sed -i "s|repository: .*frontend.*|repository: ghcr.io/${{ github.repository }}/frontend|" charts/numberninja/values.yaml
          
          # Update backend tag
          sed -i "0,/tag: \".*\"/s//tag: \"$BACKEND_VERSION\"/" charts/numberninja/values.yaml
          # Update frontend tag (second occurrence)
          sed -i "0,/tag: \".*\"/s//tag: \"$FRONTEND_VERSION\"/" charts/numberninja/values.yaml

      - name: Commit version bump
        run: |
          NEW_VERSION=$(cat charts/numberninja/VERSION)
          BACKEND_VERSION="${{ steps.image_versions.outputs.backend_version }}"
          FRONTEND_VERSION="${{ steps.image_versions.outputs.frontend_version }}"
          
          git add charts/numberninja/VERSION charts/numberninja/Chart.yaml charts/numberninja/values.yaml
          git commit -m "🔖 Bump chart version to $NEW_VERSION

          References:
          - backend: $BACKEND_VERSION
          - frontend: $FRONTEND_VERSION
          
          🤖 Generated by version-bump workflow"
          git push