apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "numberninja.fullname" . }}-frontend
  labels:
    {{- include "numberninja.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "numberninja.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "numberninja.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "numberninja.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          env:
            - name: VITE_API_URL
              value: {{ if .Values.frontend.env.VITE_API_URL }}{{ .Values.frontend.env.VITE_API_URL | quote }}{{ else }}"http://{{ include "numberninja.fullname" . }}-backend:{{ .Values.service.backend.port }}"{{ end }}
            - name: VITE_ALLOWED_HOSTS
              value: {{ if .Values.frontend.env.VITE_ALLOWED_HOSTS }}{{ .Values.frontend.env.VITE_ALLOWED_HOSTS | quote }}{{ else }}{{- $hosts := list -}}{{- range .Values.ingress.hosts -}}{{- $hosts = append $hosts .host -}}{{- end }}{{ join "," $hosts | quote }}{{ end }}
            - name: PORT
              value: "{{ .Values.frontend.port }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}