apiVersion: v1
kind: Service
metadata:
  name: {{ include "numberninja.fullname" . }}-frontend
  labels:
    {{- include "numberninja.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "numberninja.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend